# a Courtesy of Respect/Foundation

language: php

env: FOUNDATION_NO_WAIT=1

php:
  - 5.3
  - 5.4

before_script:
  - make composer-install

script:
  - make testdox

notifications:
  irc:
    channels:
      - "irc.freenode.org#php-respect"
    use_notice: true
